In [1]:
import numpy as np
Food = np.array([[56.0, 0.0, 4.4, 68.0],
                 [1.2, 104.0, 52.0, 8.0],
                 [1.8, 135.0, 99.0, 0.9]])

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [4]:
cal = Food.sum(axis=0)
percentage = 100 * Food/cal.reshape(1,4)
print(percentage) # finding calories in terms of fat, protein & carb

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [36]:
# Boradcasting 101
column = np.array([[1],[2],[3],[4]]) # 1x4
row = np.array([1,2,3,4]) # 1x4
mix = np.array([[1,2,3],[4,5,6]])

print('Simple Column broadcasting\n',column * 100)
print('\nSimple Row broadcasting\n',row * 100)

print('\nColumn with row broadcasting\n', column * np.array([100,200,300]))
print('\nRow with column broadcasting\n',row * np.array([[100],[200],[300]]))

Simple Column broadcasting
 [100 200 300 400]

Simple Row broadcasting
 [[100]
 [200]
 [300]
 [400]]


ValueError: operands could not be broadcast together with shapes (4,) (3,) 