In [2]:
import numpy as np
Food = np.array([[56.0, 0.0, 4.4, 68.0],
                 [1.2, 104.0, 52.0, 8.0],
                 [1.8, 135.0, 99.0, 0.9]])

In [4]:
cal = Food.sum(axis=0)
percentage = 100 * Food/cal.reshape(1,4)
print(percentage) # finding calories in terms of fat, protein & carb

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [37]:
# Boradcasting 101
column = np.array([[1],[2],[3],[4]]) # 4x1
row = np.array([1,2,3,4]) # 1x4
mix = np.array([[1,2,3],[4,5,6]])

print('Simple Column broadcasting\n',column * 100)
print('\nSimple Row broadcasting\n',row * 100)

print('\nColumn with row broadcasting\n', column * np.array([100,200,300])) # 1x4 * 3x1 = 4x3
print('\nRow with column broadcasting\n',row * np.array([[100],[200],[300]])) # 1x1

Simple Column broadcasting
 [[100]
 [200]
 [300]
 [400]]

Simple Row broadcasting
 [100 200 300 400]

Column with row broadcasting
 [[ 100  200  300]
 [ 200  400  600]
 [ 300  600  900]
 [ 400  800 1200]]

Row with column broadcasting
 [[ 100  200  300  400]
 [ 200  400  600  800]
 [ 300  600  900 1200]]


In [14]:
# Rank 1 array
a = np.random.randn(5)
print(a)
print(a.shape)
print(a.T, end='\n')

b = np.random.randn(5,1)
print(b)
print(b.shape)
print(b.T)

print(np.dot(b,b.T))

[ 2.22318702 -0.37733579 -0.02733205 -1.63862476  0.04764803]
(5,)
[ 2.22318702 -0.37733579 -0.02733205 -1.63862476  0.04764803]
[[-0.19098049]
 [-1.59840929]
 [ 0.92032042]
 [ 1.05918303]
 [-1.4886167 ]]
(5, 1)
[[-0.19098049 -1.59840929  0.92032042  1.05918303 -1.4886167 ]]
[[ 0.03647355  0.305265   -0.17576325 -0.2022833   0.28429675]
 [ 0.305265    2.55491225 -1.4710487  -1.69300799  2.37941876]
 [-0.17576325 -1.4710487   0.84698967  0.97478777 -1.37000434]
 [-0.2022833  -1.69300799  0.97478777  1.1218687  -1.57671755]
 [ 0.28429675  2.37941876 -1.37000434 -1.57671755  2.21597969]]


In [18]:
# Rank 1 array 
rank = np.random.randn(5)
column = np.random.randn(5,1)
row = np.random.randn(1,5)
print(np.shape(rank), np.shape(column), np.shape(row)) # we did similar on above code block

(5,) (5, 1) (1, 5)
[[-0.31459268  2.38790577  0.34502484  0.93410049 -0.89169761]]
